# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beardrive < Formula
  desc "BearDrive: a synced file system for AI agents — mount, sync, and track folders"
  homepage "https://github.com/runbear-io/beardrive"
  version "0.3.1"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runbear-io/beardrive/releases/download/v0.3.1/beardrive_0.3.1_darwin_amd64.tar.gz"
      sha256 "75079bc3f2cc0b9eaf728f2e284252582c30d1e7c4ee53f4e8cd788d55f4cc50"

      define_method(:install) do
        bin.install "bdrive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runbear-io/beardrive/releases/download/v0.3.1/beardrive_0.3.1_darwin_arm64.tar.gz"
      sha256 "e5dc31aa642280779ab3691bf2bf4e31d2fbde8aa63a8d66c4ce7df9f9bb0b47"

      define_method(:install) do
        bin.install "bdrive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbear-io/beardrive/releases/download/v0.3.1/beardrive_0.3.1_linux_amd64.tar.gz"
      sha256 "70dcd8058561300386c3aefcbda47410df83cd93c941e9d1f74aaf2a74af7a5c"
      define_method(:install) do
        bin.install "bdrive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbear-io/beardrive/releases/download/v0.3.1/beardrive_0.3.1_linux_arm64.tar.gz"
      sha256 "0a082274f82f5a2f0ea1bb5667dede11ecc5fa78386738d421ec5e37ac852cf4"
      define_method(:install) do
        bin.install "bdrive"
      end
    end
  end

  test do
    assert_match "beardrive", shell_output("#{bin}/bdrive version")
  end
end
