# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beardrive < Formula
  desc "BearDrive: a synced file system for AI agents — mount, sync, and track folders"
  homepage "https://github.com/runbear-io/beardrive"
  version "0.10.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runbear-io/beardrive/releases/download/v0.10.0/beardrive_0.10.0_darwin_amd64.tar.gz"
      sha256 "0495b3b664bce9a2fe02425c6417aded078549f555fb1aa30b5a757c51903f98"

      define_method(:install) do
        bin.install "bdrive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runbear-io/beardrive/releases/download/v0.10.0/beardrive_0.10.0_darwin_arm64.tar.gz"
      sha256 "b2532ed1567c56e963bf70b7d7c2d1b80e95a04a0ca9a6aaaa129efc6191cde3"

      define_method(:install) do
        bin.install "bdrive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbear-io/beardrive/releases/download/v0.10.0/beardrive_0.10.0_linux_amd64.tar.gz"
      sha256 "8e4f0b93db9258be4b996eb7aede04d2da23475d889b0479d8a27e3984d0c72e"
      define_method(:install) do
        bin.install "bdrive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbear-io/beardrive/releases/download/v0.10.0/beardrive_0.10.0_linux_arm64.tar.gz"
      sha256 "2b5aa79ec1e7b1905c2f37602afeb14705b7a36664f38bf1ffe18c7bea07c883"
      define_method(:install) do
        bin.install "bdrive"
      end
    end
  end

  test do
    assert_match "beardrive", shell_output("#{bin}/bdrive version")
  end
end
