# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sfs < Formula
  desc "Synced file system for AI agents: mount, sync, and track folders"
  homepage "https://github.com/runbear-io/sfs"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runbear-io/sfs/releases/download/v0.1.0/sfs_0.1.0_darwin_amd64.tar.gz"
      sha256 "72ed11e1c5f85e758d0231743684a232b8266036fd72bb24458ce89102d1cf8f"

      define_method(:install) do
        bin.install "sfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runbear-io/sfs/releases/download/v0.1.0/sfs_0.1.0_darwin_arm64.tar.gz"
      sha256 "a36c80a5f16c2f06a7e6ac82c7ddbf2221552927c9930a8d0e414bf2ddcb28b8"

      define_method(:install) do
        bin.install "sfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbear-io/sfs/releases/download/v0.1.0/sfs_0.1.0_linux_amd64.tar.gz"
      sha256 "49cbb79364215509a1b8a65c7f5ab65ea97368a39bdc42607fd6cbd1f72a437e"
      define_method(:install) do
        bin.install "sfs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbear-io/sfs/releases/download/v0.1.0/sfs_0.1.0_linux_arm64.tar.gz"
      sha256 "0d42007daa2e2bdc48081059859a0b91482ae82b9446883ba108b2078945bb32"
      define_method(:install) do
        bin.install "sfs"
      end
    end
  end

  test do
    assert_match "sfs", shell_output("#{bin}/sfs version")
  end
end
